# Generated by Django 5.1.3 on 2024-11-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_id_alter_coupon_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('P', 'Phones'), ('C', 'Cases'), ('RP', 'Replacement Parts')], max_length=2),
        ),
    ]
