# Generated by Django 5.1.4 on 2024-12-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_discount_price_item_slug_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Phones', 'Phones'), ('Cases', 'Cases'), ('Replacement Parts', 'Replacement Parts')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
