# Generated by Django 4.2.17 on 2025-01-01 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_category_category_alter_category_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='label',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
    migrations.AddField(
        model_name='item',
        name='category',
        field=models.ForeignKey(null=True, on_delete=models.SET_NULL, to='core.Category'),
    ),
    migrations.AlterField(
        model_name='address',
        name='apartment_address',
        field=models.CharField(blank=True, max_length=100),
    ),
    migrations.AlterField(
        model_name='address',
        name='zip',
        field=models.CharField(max_length=20),
    ),
    migrations.AlterField(
        model_name='category',
        name='image',
        field=models.ImageField(blank=True, default='default_category.jpg', null=True, upload_to=''),
    ),
    migrations.AlterField(
        model_name='category',
        name='slug',
        field=models.SlugField(blank=True, unique=True),
    ),
    migrations.AlterField(
        model_name='coupon',
        name='amount',
        field=models.DecimalField(decimal_places=2, max_digits=10),
    ),
    migrations.AlterField(
        model_name='item',
        name='category',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
    ),
    migrations.AlterField(
        model_name='item',
        name='discount_price',
        field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    ),
    migrations.AlterField(
        model_name='item',
        name='image',
        field=models.ImageField(blank=True, null=True, upload_to='items/'),
    ),
    migrations.AlterField(
        model_name='item',
        name='price',
        field=models.DecimalField(decimal_places=2, max_digits=10),
    ),
    migrations.AlterField(
        model_name='orderitem',
        name='quantity',
        field=models.PositiveIntegerField(default=1),
    ),
    migrations.AlterField(
        model_name='payment',
        name='amount',
        field=models.DecimalField(decimal_places=2, max_digits=10),
    ),
]
