# Generated by Django 4.2.17 on 2025-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_address_options_remove_category_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
    ]
