# Generated by Django 4.2.17 on 2025-01-01 16:37

from django.db import migrations

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20250101_1540'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
