# Generated by Django 4.2.17 on 2025-01-01 16:39

from django.db import migrations

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_update_migration_state'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
