# Generated by Django 4.2.17 on 2025-01-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_item_slug'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE core_item DROP COLUMN IF EXISTS title;',
            reverse_sql='ALTER TABLE core_item ADD COLUMN title varchar(255);'
        )
    ]
