# Generated by Django 4.2.17 on 2025-01-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_title_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE core_item ALTER COLUMN category_id DROP NOT NULL;',
            reverse_sql='ALTER TABLE core_item ALTER COLUMN category_id SET NOT NULL;'
        )
    ]
