# Generated by Django 4.2.17 on 2025-01-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_fix_duplicate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
    ]
